# Generated by Django 4.1.2 on 2023-05-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_password', models.TextField()),
                ('user_name', models.TextField()),
                ('user_level', models.IntegerField()),
                ('login_status', models.TextField()),
                ('is_delete', models.IntegerField()),
            ],
            options={
                'db_table': 'admin_user',
            },
        ),
    ]
