# Generated by Django 4.1.2 on 2023-04-05 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_csv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
