# Generated by Django 4.1.2 on 2023-04-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_csv', '0004_alter_product_id_alter_product_price_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.TextField(),
        ),
    ]
