# Generated by Django 4.1.2 on 2023-04-16 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_csv', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='product',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='product',
            name='paper',
        ),
    ]
