# Generated by Django 4.1.2 on 2023-04-18 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_csv', '0007_remove_product_cover_remove_product_isbn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
