# Generated by Django 4.1.2 on 2023-05-01 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='product_quantity',
        ),
    ]
